
language: cpp
os: linux
dist: xenial
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

cache:
    apt: true

#install:
#  - make -j2
#  - sudo make install

script:
  # Debug mode.
  - make -j2
  - sudo make install
  - esteh --version
  #- make test

  # # Clean up.
  # - make clean
  # - sudo make uninstall

  # # Release mode.
  # - sed -i '/^DEBUG_MODE/c\DEBUG_MODE = 0' Makefile
  # - make -j2
  # - sudo make install
  # - esteh --version
  # - make test
  # - git reset --hard
notifications:
  email:
    recipients:
      - ammarfaizi2@gmail.com
    on_success: change
    on_failure: always
