#!/usr/bin/env bash

# This file is not finished yet, please don't use it.
echo "This file is not finished yet, please don't use it."

# set -e

# COMPILER=g++
# LINKER=g++
# COMPILER_FLAGS="-Wall -c -g -std=c++11 -fpic"
# LINKER_FLAGS=""
# TARGET="$(pwd)/hako"
# SRC_DIR="src/"
# INCLUDE_DIR="include/"

# RM="rm -vf"
# CP="cp -vf"
# LN="ln -vfs"
# MKDIR="mkdir -vp"


# echo "#Generated by build.sh" 	> Makefile
# echo "\nCOMPILER=\"$COMPILER\"" >> Makefile
# echo "LINKER=\"$LINKER\"" 		>> Makefile
# echo "\nCOMPILER_FLAGS=$COMPILER_FLAGS"
